### ISSUE TITLE
Suggestion: Extract p-value from common test objects?

### ISSUE THREAD

**Issue by mmrabe** [gasparl/possa#11]
An obvious strength of the package is its flexibility to perform power analyses for almost any number of pretty much any statistical test in R. However, this requires that the user code their own test function such as:

```R
customTest = function(sample1) {
  c(
    a = t.test(...)$p.value,
    b = aov(...)[[1]][[1]][["Pr(>F)"]][2]
  )
}
```

As you also point out in your vignettes, this can be somewhat tricky for ANOVA or regression fits but even adding the unusual `$p.value` after the t-test call might be somewhat difficult to understand for the average R user. Would there perhaps be a way of supplying some wrapper function that automatically extracts the desired p-value from common (not all) test objects so that the user can just write something like the following?

```R
customTest = function(sample1) {
  c(
    a = extract(t.test(...)),
    b = extract(aov(...), "FactorA:FactorB")
  )
}
```

This relates to the JOSS submission openjournals/joss-reviews#4643.

**Comment by gasparl** [comment]
Okay, I now [included](https://github.com/gasparl/possa/commit/8cc765587efa8633c2a0ccb5f6ab6a02f85e7f9d#diff-f0344f97a72f579bfdfdbbef0ba51b1659a5ece74fa262e130fcf9b0455ab095) a function for this. Currently, it only supports R `stats` functions (including the particularly complicated `aov`). It'd of course be hassle to do it for each test separately, but I guess anyone who is more familiar with specific tests could fairly easily contribute with more, now that the template is there.

I might note however two drawbacks (for future considerations):
a) I realize this is not usual or likely (especially for R `stats`), but even so, if anything changes in other packages, it might take the wrong value (e.g., a different effect in the ANOVA) without the user noticing, which would be extremely problematic. Of course, this could be tested via the automated tests, but that doesn't at all guarantee the corrections will be done in time, let alone installed by users. Anyway, I included cautionary notes in the function description.
b) At tens of thousands of iterations, this could add a little time (though not much, in my `aov` testings it added like 30 sec at 45000 iterations).

**Comment by mmrabe** [comment]
Wonderful! I agree, this can be dangerous. It baffles me that there is no standard way of extracting p-values from statistical models in R, in contrast to coefficients for example. I do appreciate the your effort of including such a method, which may make the construction of the test function easier for some users.
