### ISSUE TITLE
JOSS: Conflicting (?) LICENSE files

### ISSUE THREAD

**Issue by mmrabe** [gasparl/possa#9]
Your repo contains two LICENSE files, one plain-text (as required by JOSS) and one in Markdown (.md). Do you really need both? If so, could you make sure that the plain-text file is identical to the other?

This relates to JOSS submission openjournals/joss-reviews#4643

**Comment by gasparl** [comment]
Hm I remember there was originally (years ago, for another package) some reason for this related to [CRAN](https://cran.r-project.org/) requirements, but I can't recall nor find it.. (Maybe it's not applicable anymore..)
Anyway, I just [corrected](https://github.com/gasparl/possa/commit/f049bd98bf76002dd8e145bbf09164410fc51dd1) this to have one file.
